### ISSUE TITLE
Link to Docker image not found

### ISSUE THREAD

**Issue by jzilly** [duckietown/challenge-aido_LF#1]
When running `make test` it does not find a required docker image called "duckietown/gym-duckietown-server-python3:aido2_lf_r1". Likely the correct link has changed. See error message below: 

```
Building simulator
Step 1/7 : FROM duckietown/gym-duckietown-server-python3:aido2_lf_r1
ERROR: Service 'simulator' failed to build: manifest for duckietown/gym-duckietown-server-python3:aido2_lf_r1 not found
make: *** [test] Error 1
```

**Comment by tanij** [comment]
Hi @jzilly , has this issue been solved? (please close if so)

**Comment by jzilly** [comment]
Yes. The issue is that one has to add the option "--pull" when building docker images. Otherwise updates to the base image are not "pulled" which caused the error above.
